[tool.poetry]
name = "zyx"
version = "0.2.20"
description = "AI"
authors = ["Hammad Saeed <hammad@supportvectors.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.9"
ollama = "^0.3.1"
openai = "^1.40.1"
peewee = "^3.17.6"
phidata = "^2.4.29"
loguru = "^0.7.2"
rich = "^13.7.1"
sqlmodel = "^0.0.21"
qdrant-client = "^1.10.1"

[tool.poetry.group.dev.dependencies]
poetry = "^1.8.3"
ruff = "^0.5.6"
uv = "^0.2.33"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
